In [1]:
import tensorflow as tf

session = tf.Session()

In [2]:
# Scalar

a = tf.constant(1)
session.run(a)

1

In [3]:
session.run(tf.rank(a))

0

In [4]:
a.shape

TensorShape([])

In [5]:
# Vector (1D)

b = tf.constant([1, 2, 3])
session.run(b)

array([1, 2, 3], dtype=int32)

In [6]:
session.run(tf.rank(b))

1

In [7]:
b.shape

TensorShape([Dimension(3)])

In [8]:
# Matrix (2D)

c = tf.constant([[1, 2, 3], [4, 5, 6]])
session.run(c)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [9]:
session.run(tf.rank(c))

2

In [10]:
c.shape

TensorShape([Dimension(2), Dimension(3)])

In [11]:
# 3D array

d = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
session.run(d)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)

In [12]:
session.run(tf.rank(d))

3

In [13]:
d.shape

TensorShape([Dimension(2), Dimension(2), Dimension(3)])

In [14]:
# Python의 더하기 (concatenation)

a = [1, 2]
b = [3, 4]
a + b

[1, 2, 3, 4]

In [15]:
a = [1, 2]
b = 3
# a + b  # => Error!

In [16]:
a = [1, 2]
b = [3]
a + b

[1, 2, 3]

In [17]:
a = [1, 2]
b = [3, 4, 5]
a + b

[1, 2, 3, 4, 5]

In [18]:
# TensorFlow의 더하기 (addition)

a = tf.constant([1, 2])
b = tf.constant([3, 4])
session.run(a + b)

array([4, 6], dtype=int32)

In [19]:
a = tf.constant([1, 2])
b = tf.constant(3)
session.run(a + b)

array([4, 5], dtype=int32)

In [20]:
a = tf.constant([1, 2])
b = tf.constant([3])
session.run(a + b)

array([4, 5], dtype=int32)

In [21]:
a = tf.constant([1, 2])
b = tf.constant([3, 4, 5])
# session.run(a + b)  # => Error!

In [22]:
# Python의 곱하기 (repeat)

a = [1, 2]
b = [3, 4]
# a * b  # => Error!

In [23]:
a = [1, 2]
b = 3
a * b

[1, 2, 1, 2, 1, 2]

In [24]:
a = [1, 2]
b = [3, 4, 5]
# a * b  # => Error!

In [25]:
# TensorFlow의 곱하기 (multiplication)

a = tf.constant([1, 2])
b = tf.constant([3, 4])
session.run(a * b)

array([3, 8], dtype=int32)

In [26]:
a = tf.constant([1, 2])
b = tf.constant(3)
session.run(a * b)

array([3, 6], dtype=int32)

In [27]:
a = tf.constant([1, 2])
b = tf.constant([3])
session.run(a * b)

array([3, 6], dtype=int32)

In [28]:
a = tf.constant([1, 2])
b = tf.constant([3, 4, 5])
# session.run(a * b)  # => Error!

In [29]:
# TensorFlow의 곱하기 (dot product)

a = tf.constant([[1, 2]])
b = tf.constant([[3], [4]])
session.run(tf.matmul(a, b))

array([[11]], dtype=int32)

In [30]:
a = tf.constant([[1], [2]])
b = tf.constant([[3, 4]])
session.run(tf.matmul(a, b))

array([[3, 4],
       [6, 8]], dtype=int32)

In [31]:
# 선형결합 (linear combination)

quantity = tf.constant([[1, 2, 3]])
price = tf.constant([[2000], [1500], [1000]])
session.run(tf.matmul(quantity, price))

array([[8000]], dtype=int32)

In [32]:
quantity = tf.constant([[1, 2, 3], [1, 1, 1], [0, 0, 0], [3, 2, 1]])
price = tf.constant([[2000], [1500], [1000]])
session.run(tf.matmul(quantity, price))

array([[ 8000],
       [ 4500],
       [    0],
       [10000]], dtype=int32)

In [33]:
quantity = tf.constant([[1, 2, 3], [1, 1, 1], [0, 0, 0], [3, 2, 1]])
price = tf.constant([[2000, 200], [1500, 150], [1000, 100]])
session.run(tf.matmul(quantity, price))

array([[ 8000,   800],
       [ 4500,   450],
       [    0,     0],
       [10000,  1000]], dtype=int32)